import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';
import api from '../services/api';
import { useAuth } from './AuthContext';

const ChatContext = createContext();

export const ChatProvider = ({ children }) => {
  const { user } = useAuth();
  const [chats, setChats] = useState([]);
  const [activeChatId, setActiveChatId] = useState(null);
  const [currentChat, setCurrentChat] = useState(null);
  const [loadingAI, setLoadingAI] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  
  // Monaco Split Editor state
  const [showEditor, setShowEditor] = useState(false);
  const [editorCode, setEditorCode] = useState('// Write or paste code here...\nfunction helloCodeSphere() {\n  console.log("Welcome to CodeSphere AI!");\n}\n\nhelloCodeSphere();');
  const [editorLanguage, setEditorLanguage] = useState('javascript');
  const [editorOutput, setEditorOutput] = useState(null);

  // Modals & Panels
  const [toolsModalOpen, setToolsModalOpen] = useState(false);
  const [settingsModalOpen, setSettingsModalOpen] = useState(false);
  const [sidebarOpen, setSidebarOpen] = useState(true);

  // Load chat history when user changes
  const fetchChats = useCallback(async () => {
    if (!user || user._id === 'guest_user_101') {
      // Local demo chats for guest
      const sampleChat = {
        _id: 'guest_chat_1',
        title: 'Python Binary Search',
        messages: [
          { role: 'user', content: 'Create a binary search function in Python.' },
          {
            role: 'assistant',
            content: `Here is the binary search implementation in Python:

\`\`\`python
def binary_search(arr, target):
    left = 0
    right = len(arr) - 1

    while left <= right:
        mid = (left + right) // 2

        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            left = mid + 1
        else:
            right = mid - 1

    return -1

# Example usage
nums = [1, 3, 5, 7, 9, 11]
print(binary_search(nums, 7)) # Output: 3
\`\`\``
          }
        ]
      };
      setChats([sampleChat]);
      setActiveChatId(sampleChat._id);
      setCurrentChat(sampleChat);
      return;
    }

    try {
      const res = await api.get('/chats');
      setChats(res.data);
      if (res.data.length > 0 && !activeChatId) {
        selectChat(res.data[0]._id);
      }
    } catch (err) {
      console.warn('Failed to load chat history:', err.message);
    }
  }, [user]);

  useEffect(() => {
    fetchChats();
  }, [fetchChats]);

  const selectChat = async (id) => {
    setActiveChatId(id);
    if (!user || user._id === 'guest_user_101') {
      const found = chats.find(c => c._id === id);
      if (found) setCurrentChat(found);
      return;
    }

    try {
      const res = await api.get(`/chats/${id}`);
      setCurrentChat(res.data);
    } catch (err) {
      console.error('Error fetching chat detail:', err);
    }
  };

  const createNewChat = () => {
    setActiveChatId(null);
    setCurrentChat(null);
  };

  const sendMessage = async (messageText, attachment = null) => {
    const trimmedMessage = messageText.trim();
    if (!trimmedMessage && !attachment) return;

    setLoadingAI(true);

    const tempUserMsg = {
      role: 'user',
      content: trimmedMessage + (attachment ? `\n\n[Attached: ${attachment.name}]` : ''),
      createdAt: new Date().toISOString(),
    };

    // Update UI immediately for responsiveness
    setCurrentChat(prev => {
      const existing = prev ? prev.messages : [];
      return {
        _id: activeChatId || 'temp_chat',
        title: prev ? prev.title : messageText.slice(0, 30),
        messages: [...existing, tempUserMsg],
      };
    });

    try {
      if (user && user._id !== 'guest_user_101') {
        const res = await api.post('/chat', {
          chatId: activeChatId,
          message: trimmedMessage,
          attachment,
        });

        setActiveChatId(res.data.chatId);
        setCurrentChat({
          _id: res.data.chatId,
          title: res.data.title,
          messages: res.data.messages,
        });

        fetchChats();
      } else {
        // Guest mode fallback response
        await new Promise(r => setTimeout(r, 1200));
        
        let aiReply = `Here is a solution for your query:

\`\`\`${editorLanguage || 'javascript'}
// Code generated by CodeSphere AI
function solveProblem() {
  console.log("Processing request: ${trimmedMessage.replace(/"/g, "'")}");
  return { status: "Success", code: 200 };
}

solveProblem();
\`\`\`

### Explanation
1. Executes the specification clearly.
2. Formatted for production build.`;

        if (trimmedMessage.toLowerCase().includes('binary search')) {
          aiReply = `Here is a binary search function in Python:

\`\`\`python
def binary_search(arr, target):
    left = 0
    right = len(arr) - 1

    while left <= right:
        mid = (left + right) // 2

        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            left = mid + 1
        else:
            right = mid - 1

    return -1
\`\`\``;
        }

        const aiMsg = {
          role: 'assistant',
          content: aiReply,
          createdAt: new Date().toISOString(),
        };

        setCurrentChat(prev => ({
          ...prev,
          messages: [...prev.messages, aiMsg],
        }));
      }
    } catch (err) {
      console.error('Error sending message:', err);
      const errorMessage = err.response?.data?.message || 'The AI service could not answer this question. Please check that the server is running and try again.';
      setCurrentChat(prev => ({
        ...prev,
        messages: [...(prev?.messages || []), {
          role: 'assistant',
          content: `I couldn't process that request.\n\n${errorMessage}`,
          createdAt: new Date().toISOString(),
        }],
      }));
    } finally {
      setLoadingAI(false);
    }
  };

  const deleteChat = async (id) => {
    try {
      if (user && user._id !== 'guest_user_101') {
        await api.delete(`/chats/${id}`);
      }
      setChats(prev => prev.filter(c => c._id !== id));
      if (activeChatId === id) {
        createNewChat();
      }
    } catch (err) {
      console.error('Failed to delete chat:', err);
    }
  };

  const renameChat = async (id, newTitle) => {
    try {
      if (user && user._id !== 'guest_user_101') {
        await api.put(`/chats/${id}`, { title: newTitle });
      }
      setChats(prev => prev.map(c => c._id === id ? { ...c, title: newTitle } : c));
      if (currentChat && currentChat._id === id) {
        setCurrentChat(prev => ({ ...prev, title: newTitle }));
      }
    } catch (err) {
      console.error('Failed to rename chat:', err);
    }
  };

  const runCodeInSandbox = async (stdin = '') => {
    setEditorOutput({ type: 'running', message: `Executing ${editorLanguage} code...` });
    try {
      const response = await api.post('/code/execute', {
        language: editorLanguage,
        code: editorCode,
        stdin,
      });
      const output = response.data.stdout || response.data.stderr || response.data.compileOutput || response.data.message;
      setEditorOutput({
        type: response.data.status === 'Accepted' ? 'success' : 'error',
        message: `Status: ${response.data.status}\n${response.data.stderr || response.data.compileOutput ? `${response.data.stderr || response.data.compileOutput}` : `Output:\n${output || '(no output)'}`}`,
      });
    } catch (err) {
      setEditorOutput({
        type: 'error',
        message: `Execution Error: ${err.response?.data?.message || err.message}`,
      });
    }
  };

  return (
    <ChatContext.Provider
      value={{
        chats,
        currentChat,
        activeChatId,
        loadingAI,
        searchQuery,
        setSearchQuery,
        selectChat,
        createNewChat,
        sendMessage,
        deleteChat,
        renameChat,
        showEditor,
        setShowEditor,
        editorCode,
        setEditorCode,
        editorLanguage,
        setEditorLanguage,
        editorOutput,
        setEditorOutput,
        runCodeInSandbox,
        toolsModalOpen,
        setToolsModalOpen,
        settingsModalOpen,
        setSettingsModalOpen,
        sidebarOpen,
        setSidebarOpen,
      }}
    >
      {children}
    </ChatContext.Provider>
  );
};

export const useChat = () => useContext(ChatContext);
